### ISSUE TITLE
NFKD truncated on Windows

### ISSUE THREAD

**Issue by swankjesse** [Doist/doistx-normalize#37]
Thanks for this awesome project. I wish I would have found it before [embarking on my own](https://github.com/square/okhttp-icu). Ugh!

Windows normalization uses [NormalizeString](https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-normalizestring). Calls to that function need a loop to defend against errors in the output size estimate. The example code shows a loop to overcome incorrect estimates.

As-is, I believe this test will fail:

```
  @Test
  fun maxExpansion() {
    val a = "(ﷺ)"
    val b = "(صلى الله عليه وسلم)"

    // Succeeds.
    assertEquals(b, a.normalize(NormalizationKD))

    // Fails.
    assertEquals(b.repeat(4), a.repeat(4).normalize(NormalizationKD))
  }
```

**Comment by goncalossilva** [comment]
Hey, thanks for reporting this! Good catch. I missed this in their docs originally. I'll work on a fix in #40.

Taking a look at `okhttp-icu`, it's also clear that test coverage is lacking here. I was unaware that `NormalizationTest.txt` existed, so now I'll be looking into incorporating it into the test suite. I suspect it will uncover other issues.
