### ISSUE TITLE
1.0.4 release not usable from Android

### ISSUE THREAD

**Issue by treitter** [Doist/doistx-normalize#5]
Hi, I'm trying to finish my initial migration of my app to KMM and have 3 different options for `normalize` but all fail for different reasons:

* 1.0.3 doesn't have compatible builds for Apple Silicon devices (which I'm building on)
* 1.0.4 has arm64 builds but requires Kotlin 1.6. Building with Kotlin 1.5.30, I get:
```
w: skipping /Users/treitter/.gradle/caches/modules-2/files-2.1/com.doist.x/normalize-iossimulatorarm64/1.0.4/c7de411ce251543941ffdda10f4116af683445d9/normalize.klib. Incompatible abi version. The current default is '1.5.0', found '1.6.0'. The library produced by 1.6.0 compiler
e: Could not find "/Users/treitter/.gradle/caches/modules-2/files-2.1/com.doist.x/normalize-iossimulatorarm64/1.0.4/c7de411ce251543941ffdda10f4116af683445d9/normalize.klib" in [/Users/treitter/myapp/ios, /Users/treitter/.konan/klib, /Users/treitter/.konan/kotlin-native-prebuilt-macos-x86_64-1.5.31/klib/common, /Users/treitter/.konan/kotlin-native-prebuilt-macos-x86_64-1.5.31/klib/platform/ios_simulator_arm64]

```
* Kotlin 1.6 is currently causing a build error unrelated to `normalize` but I can't figure out the actual cause of that failure (it seems very similar to [this error](https://stackoverflow.com/questions/67552441/no-matching-variant-of-kotlin-multiplatrom-mobile-library-found) even though I don't believe I have any dependencies in my `commonMain` that are JVM-only).

Is it possible to publish a release of `normalize` 1.0.4 built with Kotlin 1.5.x?

**Comment by treitter** [comment]
Based on [this bug](https://youtrack.jetbrains.com/issue/KT-50263), it seems most likely that the existing 1.0.4 release was built with Kotlin 1.6.0 which apparently breaks Android consumers.

The fix is apparently to build the library with Kotlin 1.6.10 or later.

**Comment by treitter** [comment]
Sorry for the noise. It turned out my underlying issue was unrelated.

**Comment by goncalossilva** [comment]
@treitter not at all, thanks for reporting! I was unaware of KT-50263.

Happy to bump to 1.6.10 if that would help your integration!
